services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: ticket-booking-postgres
    environment:
      POSTGRES_DB: ticket_booking
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ticket-booking-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    restart: unless-stopped

  # Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ticket-booking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Apache Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ticket-booking-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PROTOCOL_LOCAL://0.0.0.0:29092,PROTOCOL_DOCKER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PROTOCOL_LOCAL://localhost:29092,PROTOCOL_DOCKER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PROTOCOL_LOCAL:PLAINTEXT,PROTOCOL_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PROTOCOL_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092" # แมปพอร์ตนี้ออกมาให้ Go App ในเครื่องต่อได้

  # Kafka UI (Optional - for monitoring)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ticket-booking-kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  default:
    name: ticket-booking-network
